#!/usr/bin/env python3
"""Print frozen vectors for make_input_seeded; regeneration is an explicit review.

BLAKE3 uses the upstream reference implementation in the enclosing fork,
compiled directly with rustc. SHA-256, SHA-1, and SHA3-256 use Python hashlib. Neither
source calls the optimized servil kernels. Requires Python 3 and rustc.
Run from bench-hashes: python3 tools/gen-test-vectors.py > src/test_vectors.rs

Two tables. VECTORS: one message of each length, its digests.
MANY_VECTORS: a batch of N 64-byte messages (the buffer
make_input_seeded(64 * N, seed) cut into 64-byte slices), and for each
family the SHA-256 of the N digests concatenated in message order.
"""
import array
import hashlib
from pathlib import Path
import subprocess
import sys
import tempfile

ROOT = Path(__file__).resolve().parents[2]
REFERENCE = ROOT / "reference_impl/reference_impl.rs"
SIZES = sorted(set([1 << n for n in range(6, 28)] + [3 << 10, 3 << 20,
    0, 1, 63, 65, 1023, 1025, (16 << 10) - 1, (16 << 10) + 1,
    (64 << 10) - 1, (64 << 10) + 1, (128 << 10) + 1, (256 << 10) + 1,
    # Sizes of real data between 2 and 8 KiB (the axis's usage points):
    # an 802.11 frame body (MSDU) at most, an 802.11n A-MSDU of the smaller
    # and the larger maximum, a Packet over SONET/SDH MTU.
    2304, 3839, 7935, 4470]))
# The many-messages axis in src/main.rs (POINTS): its message length and
# its counts per batch.
BATCH_TABLES = [("MANY_VECTORS", 64)]
BATCHES = [1, 2, 3, 4, 6, 8, 12, 16, 24, 32, 48, 64, 128, 256, 512, 1024,
    2048, 4096, 8192, 16384, 32768, 65536, 131072, 262144]


def make_input(size, seed):
    """The benchmark's input: little-endian 64-bit words seed << 48 | index."""
    assert sys.byteorder == "little", "array('Q') packs in native byte order"
    words = array.array("Q", range(seed << 48, (seed << 48) + (size + 7) // 8))
    return words.tobytes()[:size]


with tempfile.TemporaryDirectory() as tmp:
    tmp = Path(tmp)
    lib = tmp / "libreference_impl.rlib"
    subprocess.run(["rustc", "--edition=2024", "--crate-name=reference_impl",
        "--crate-type=rlib", "-O", str(REFERENCE), "-o", str(lib)], check=True)
    driver = tmp / "hash.rs"
    # With no argument: one digest of stdin. With a message length: one
    # digest per line for each slice of that length, in order.
    driver.write_text('''use std::io::Read;
fn main() {
    let mut input = Vec::new();
    std::io::stdin().read_to_end(&mut input).unwrap();
    let message_len: usize = std::env::args().nth(1).map(|n| n.parse().unwrap()).unwrap_or(input.len());
    let messages: Vec<&[u8]> = if input.is_empty() { vec![&input[..]] } else { input.chunks_exact(message_len).collect() };
    assert_eq!(messages.len() * message_len.max(1), input.len().max(1));
    for message in messages {
        let mut hasher = reference_impl::Hasher::new();
        hasher.update(message);
        let mut out = [0u8; 32];
        hasher.finalize(&mut out);
        for b in out { print!("{b:02x}"); }
        println!();
    }
}
''')
    binary = tmp / "hash"
    subprocess.run(["rustc", "--edition=2024", "-O", str(driver), "--extern",
        f"reference_impl={lib}", "-o", str(binary)], check=True)
    print("// Generated by tools/gen-test-vectors.py; review changes as golden data.")
    print("// BLAKE3 reference source SHA-256: " + hashlib.sha256(REFERENCE.read_bytes()).hexdigest())
    print("// Input: make_input_seeded(length, seed): little-endian u64 words seed << 48 | index. Digests: BLAKE3, SHA-256, SHA-1, SHA3-256.")
    print("pub(super) const VECTORS: &[(usize, u64, [&str; 4])] = &[")
    for size in SIZES:
        for seed in [0, 1]:
            data = make_input(size, seed)
            b3 = subprocess.run([str(binary)], input=data, stdout=subprocess.PIPE,
                check=True).stdout.decode().strip()
            assert len(b3) == 64
            digests = [b3, hashlib.sha256(data).hexdigest(), hashlib.sha1(data).hexdigest(), hashlib.sha3_256(data).hexdigest()]
            print(f'    ({size}, {seed}, ["' + '", "'.join(digests) + '"]),')
    print("];")
    for table, message_len in BATCH_TABLES:
        print()
        print(f"// Batches of N {message_len}-byte messages: SHA-256 over the N concatenated digests. Digests: BLAKE3, SHA-256, SHA-1, SHA3-256.")
        print(f"pub(super) const {table}: &[(usize, u64, [&str; 4])] = &[")
        for count in BATCHES:
            for seed in [0, 1]:
                data = make_input(message_len * count, seed)
                messages = [data[i:i + message_len] for i in range(0, len(data), message_len)]
                b3_lines = subprocess.run([str(binary), str(message_len)], input=data,
                    stdout=subprocess.PIPE, check=True).stdout.decode().split()
                assert len(b3_lines) == count
                b3 = b"".join(bytes.fromhex(line) for line in b3_lines)
                sha256 = b"".join(hashlib.sha256(m).digest() for m in messages)
                sha1 = b"".join(hashlib.sha1(m).digest() for m in messages)
                sha3 = b"".join(hashlib.sha3_256(m).digest() for m in messages)
                folded = [hashlib.sha256(d).hexdigest() for d in (b3, sha256, sha1, sha3)]
                print(f'    ({count}, {seed}, ["' + '", "'.join(folded) + '"]),')
        print("];")
